/* Quantities are stored in the SKU's selling unit. Unit definitions are immutable after first save. */
(function(w){'use strict';const A=w.App,D=A.domain,UNITS={piece:['count',1],pack:['pack',1],kg:['mass',1000],g:['mass',1],l:['volume',1000],ml:['volume',1]};
 const spec=it=>it.quantitySpec||(UNITS[it.unit]?{version:1,unit:it.unit}:null);
 function validate(it){const s=it.quantitySpec;if(s===undefined)return;if(!s||typeof s!=='object'||Array.isArray(s)||s.version!==1||!UNITS[s.unit]||it.unit!==s.unit||Object.keys(s).some(k=>!['version','unit','packSize','packUnit'].includes(k)))throw Error('Invalid selling-unit definition.');if(s.unit==='pack'){if(!UNITS[s.packUnit]||s.packUnit==='pack'||!Number.isFinite(s.packSize)||s.packSize<=0)throw Error('Define the contents of one pack.');D.quantityUnits(s.packSize);if(s.packUnit==='piece'&&!Number.isInteger(s.packSize))throw Error('Pack contents in pieces require whole quantities.');}else if(s.packSize!==undefined||s.packUnit!==undefined)throw Error('Pack contents require the pack selling unit.');for(const q of [it.stock,...(it.batches||[]).map(b=>b.qty)])assertQuantity(it,q);}
 function assertQuantity(it,q){D.quantityUnits(q);const s=spec(it);if(it.quantitySpec&&['piece','pack'].includes(s.unit)&&!Number.isInteger(q))throw Error('Pieces and packs require whole quantities.');}
 function positive(q){const n=D.quantityUnits(q);if(n===0)throw Error('Quantity is too small for supported precision.');return n/D.QUANTITY_SCALE;}
 function convert(it,amount,spokenUnit){const s=spec(it);if(!Number.isFinite(amount)||amount<=0)throw Error('Quantity must be greater than zero.');if(!spokenUnit){assertQuantity(it,amount);return positive(amount);}if(!s){if(['piece','pack'].includes(spokenUnit)){return positive(amount);}throw Error('Set an explicit selling unit before using measured voice quantities.');}let q;if(spokenUnit===s.unit)q=amount;else if(s.unit==='pack'){if(!s.packUnit)throw Error('Define the contents of one pack.');if(UNITS[spokenUnit]?.[0]!==UNITS[s.packUnit]?.[0])throw Error('Spoken and selling units are incompatible.');q=amount*UNITS[spokenUnit][1]/(s.packSize*UNITS[s.packUnit][1]);}else{if(UNITS[spokenUnit]?.[0]!==UNITS[s.unit]?.[0])throw Error('Spoken and selling units are incompatible.');q=amount*UNITS[spokenUnit][1]/UNITS[s.unit][1];}q=positive(q);assertQuantity(it,q);return q;}
 A.units={names:()=>Object.keys(UNITS),spec,validate,assertQuantity,convert,label:it=>{const s=spec(it);return s?s.unit==='pack'?'pack ('+s.packSize+' '+s.packUnit+')':s.unit:'unit';},
  validateBook(db){if(db.quantityVersion!==undefined&&db.quantityVersion!==1)throw Error('Unsupported quantity-unit version.');for(const it of db.items){if(it.quantitySpec!==undefined&&db.quantityVersion!==1)throw Error('Selling units require the versioned book marker.');validate(it);}for(const bill of db.bills)for(const line of bill.lines){if(line.quantitySpec!==undefined&&db.quantityVersion!==1)throw Error('Selling units require the versioned book marker.');validate({...line,stock:line.qty,batches:[]});}},
  guard(previous,db,restoring){if(restoring||!previous)return;const before=JSON.parse(previous);for(const it of db.items){const old=before.items.find(i=>i.id===it.id);if(old&&JSON.stringify(old.quantitySpec)!==JSON.stringify(it.quantitySpec))throw Error('Selling units cannot change on an existing item. Create a new item.');}},
  compatible:(a,b)=>JSON.stringify(spec(a))===JSON.stringify(spec(b))
 };
 A.registerUIWords({'Selling unit':'बिक्री की इकाई','Legacy unit (unchanged)':'पुरानी इकाई (बिना बदलाव)','Contents per pack':'एक पैक में मात्रा','Pack contents unit':'पैक की सामग्री की इकाई','Selling units cannot change on an existing item. Create a new item.':'पुराने सामान की बिक्री इकाई नहीं बदल सकती। नया सामान बनाएँ।','Pieces and packs require whole quantities.':'पीस और पैक की मात्रा पूरी संख्या होनी चाहिए।','Set an explicit selling unit before using measured voice quantities.':'बोलकर माप वाली मात्रा देने से पहले बिक्री की इकाई तय करें।','Spoken and selling units are incompatible.':'बोली गई और बिक्री की इकाइयाँ मेल नहीं खातीं।','Define the contents of one pack.':'एक पैक में सामग्री की मात्रा तय करें।'});
})(window);
