const {test}=require('node:test'),assert=require('node:assert/strict');
const {create,item,customer,supplier,cart}=require('./harness.cjs');
test('VERIFY-13: optional browser-language write failure does not report a durable settings save as failed',async()=>{
 const {A,ctx,storage}=await create();ctx.document.documentElement={};const set=ctx.localStorage.setItem;ctx.localStorage.setItem=(k,v)=>{if(k==='dukaanos.uiLanguage')throw Error('Preference unavailable');set(k,v);};await A.setLang('hi');assert.equal(A.lang(),'hi');assert.equal(JSON.parse(storage.get('dukaanos.v2.audit')).settings.lang,'hi');assert.equal(ctx.document.documentElement.lang,'hi');
});
test('VERIFY-13: Hindi transactions retain reconciled customer, supplier, return, transfer, stock and cash histories across language changes',async()=>{
 const {A,ctx}=await create();ctx.document.documentElement={};const i=item(A,{stock:0}),c=customer(A,{balance:200}),s=supplier(A);A.DB().stores.push({id:'branch',name:'Branch'});A.DB().settings.gstEnabled=true;await A.save();await A.setLang('hi');await A.actions.startStockHistory();const shift=await A.actions.openCashShift({openingFloat:500,note:'Synthetic float'});
 const purchase=await A.actions.recordPurchase(s.id,[{itemId:i.id,qty:10,cost:60}],200,'','cash'),sale=await A.actions.checkout({...cart(i),lines:[{itemId:i.id,qty:2,price:100}]});await A.actions.checkout(cart(i,{mode:'credit',customerId:c.id}));await A.actions.takePayment(c.id,50,'cash');const ret=await A.actions.returnSale({billId:sale.id,lines:[{lineId:sale.lines[0].lineId,qty:1}],reason:'Synthetic return'});await A.actions.settleReturn(ret.id,105,'cash','Synthetic refund');await A.actions.returnPurchase({purchaseId:purchase.id,lines:[{lineId:purchase.lines[0].lineId,qty:2}],reason:'Synthetic supplier return'});const lot=A.stockLots(i)[0];await A.actions.adjustStock({itemId:i.id,batchId:lot.id,count:lot.qty-1,note:'Synthetic count'});const transfer=await A.actions.sendTransfer({toStoreId:'branch',lines:[{itemId:i.id,qty:1}],note:'Synthetic dispatch'});await A.actions.switchStore('branch');await A.actions.receiveTransfer({transferId:transfer.id,lines:[{lineId:transfer.lines[0].lineId,qty:1}],note:'Synthetic receipt'});await A.actions.switchStore('st_main');await A.actions.cashEntry({amount:30,note:'Synthetic expense'});await A.actions.closeCashShift({shiftId:shift.id,counted:420,note:'Synthetic close'});
 const r=A.reconcileBook();assert.deepEqual(JSON.parse(JSON.stringify([r.sales.sales,r.sales.tax,r.sales.profit,r.customers[0].actual,r.suppliers[0].actual,r.stock[0].actual,r.shifts[0].expected,r.shifts[0].variance,r.differences.length])),[210,10,80,255,280,4,425,-5,0]);const snapshot=JSON.stringify([A.DB().bills,A.DB().stockBook,A.DB().cashSessions,A.DB().customers,A.DB().suppliers]),receipt=A.billText(sale);await A.setLang('en');assert.equal(JSON.stringify([A.DB().bills,A.DB().stockBook,A.DB().cashSessions,A.DB().customers,A.DB().suppliers]),snapshot);assert.equal(A.billText(sale),receipt);
});
