const {test}=require('node:test'),assert=require('node:assert/strict');
const {create,item,customer,supplier,cart}=require('./harness.cjs');
function clock(ctx){let now=Date.parse('2026-09-11T10:00:00Z');ctx.Date=class extends Date{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}};return value=>now=Date.parse(value);}
test('BUILD-12: full shop day reconciles statements, stock journal, cash and dated corrections',async()=>{
 const {A,ctx}=await create(),tick=clock(ctx),i=item(A,{stock:0}),c=customer(A,{balance:200}),s=supplier(A);A.DB().settings.gstEnabled=true;A.DB().stores.push({id:'branch',name:'Branch'});await A.save();await A.actions.startStockHistory();const shift=await A.actions.openCashShift({openingFloat:500,note:'Counted shop float'});
 const purchase=await A.actions.recordPurchase(s.id,[{itemId:i.id,qty:10,cost:60}],200,'','cash');const sale=await A.actions.checkout({...cart(i),lines:[{itemId:i.id,qty:2,price:100}]}),receipt=A.billText(sale);const credit=await A.actions.checkout(cart(i,{mode:'credit',customerId:c.id}));await A.actions.takePayment(c.id,50,'cash');
 const ret=await A.actions.returnSale({billId:sale.id,lines:[{lineId:sale.lines[0].lineId,qty:1}],reason:'One item returned'});await A.actions.settleReturn(ret.id,105,'cash','Refund handed back');await A.actions.returnPurchase({purchaseId:purchase.id,lines:[{lineId:purchase.lines[0].lineId,qty:2}],reason:'Two units sent back'});const lot=A.stockLots(i)[0];await A.actions.adjustStock({itemId:i.id,batchId:lot.id,count:lot.qty-1,note:'Shelf count short one'});
 const transfer=await A.actions.sendTransfer({toStoreId:'branch',lines:[{itemId:i.id,qty:2}],note:'Two units to branch'});await A.actions.switchStore('branch');await A.actions.receiveTransfer({transferId:transfer.id,lines:[{lineId:transfer.lines[0].lineId,qty:1}],note:'One unit arrived'});await A.actions.switchStore('st_main');await A.actions.receiveTransfer({transferId:transfer.id,lines:[{lineId:transfer.lines[0].lineId,qty:1}],recall:true,note:'Other unit returned'});
 await A.actions.cashEntry({amount:30,note:'Transport expense'});await A.actions.closeCashShift({shiftId:shift.id,counted:420,note:'Physical till count'});
 const options={from:'2026-09-11',to:'2026-09-11'},r=A.reconcileBook(options);assert.deepEqual(JSON.parse(JSON.stringify([r.sales.sales,r.sales.tax,r.sales.cost,r.sales.profit,r.cashNet])),[210,10,120,80,-75]);assert.equal(r.customers[0].expected,255);assert.equal(r.suppliers[0].expected,280);assert.equal(r.stock[0].expected,4);assert.equal(A.DB().items.find(x=>x.storeId==='branch').batches[0].qty,1);assert.equal(r.shifts[0].expected,425);assert.equal(r.shifts[0].variance,-5);assert.equal(r.differences.length,0);assert.equal(A.billText(sale),receipt);
 const rows=A.statementRows('sales',options);assert.equal(rows.slice(1).reduce((n,row)=>n+row[6],0),210);assert.equal(rows.slice(1).reduce((n,row)=>n+row[9],0),80);assert.equal(A.statementRows('stock').slice(1).filter(row=>row[1]===i.id).at(-1)[8],4);
 tick('2026-09-12T10:00:00Z');await A.actions.voidBill(credit.id,'Next day credit cancellation');assert.equal(A.salesStatement(options).sales,210);const next=A.salesStatement({from:'2026-09-12'});assert.equal(next.sales,-105);assert.equal(next.tax,-5);assert.equal(next.cost,-60);assert.equal(next.profit,-40);assert.equal(A.reconcileBook().customers[0].expected,150);assert.equal(A.reconcileBook().differences.length,0);
});
test('BUILD-12: stock checkpoint restore does not manufacture movements and failed saves are atomic',async()=>{
 const h=await create(),A=h.A,i=item(A);await A.save();await A.actions.startStockHistory();await A.actions.checkout(cart(i));const backup=A.backups.capture(),count=A.DB().stockBook.entries.length;await A.actions.restock(i.id,3);assert.equal(A.itemStock(i),12);await A.restoreBackup(backup);assert.equal(A.DB().stockBook.entries.length,count);assert.equal(A.itemStock(A.item(i.id)),9);
 const prior=JSON.stringify(A.DB()),commit=A.storage.commit;A.storage.commit=async()=>{throw new Error('Statement disk failure');};await assert.rejects(()=>A.actions.restock(i.id,1),/disk/);assert.equal(JSON.stringify(A.DB()),prior);A.storage.commit=commit;
 const fresh=await create();await fresh.A.restoreBackup(await A.backups.decrypt(await A.backups.encrypt(A.backups.capture(),'Synthetic-statement-backup'),'Synthetic-statement-backup'));assert.equal(fresh.A.reconcileBook().stock[0].expected,9);assert.equal(fresh.A.DB().stockBook.entries.length,count);
});
test('BUILD-12: legacy dates, archived accounts and fractional return costs remain explicit and complete',async()=>{
 const {A,ctx}=await create();clock(ctx);const i=item(A,{price:1,cost:0.015,stock:3}),c=customer(A,{balance:12});c.deleted=true;await A.save();assert.equal(A.statementRows('customers').length,2);assert.match(A.reconcileBook().caveats.join(' '),/historical statement|Stock history/);assert.equal(A.statementRows('stock')[1][0],'Unknown');
 await A.actions.startStockHistory();const bill=await A.actions.checkout({...cart(i),lines:[{itemId:i.id,qty:3,price:1}]});for(let n=0;n<3;n++)await A.actions.returnSale({billId:bill.id,lines:[{lineId:bill.lines[0].lineId,qty:1}],reason:'Fractional cost return'});
 const r=A.salesStatement({from:'2026-09-11'});assert.equal(r.cost,0);assert.equal(r.profit,0);assert.equal(r.sales,0);assert.equal(r.events.reduce((n,e)=>n+Math.round(e.cost*100),0),0);assert.throws(()=>A.reportPeriod({from:'2026-02-30'}),/valid/);
 const before=JSON.stringify(A.DB());A.statementRows('reconciliation');assert.equal(JSON.stringify(A.DB()),before);
});
