/* Local-only release evidence. Never reads browser storage or uploads observations. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'..'),ASSETS=require('../public-assets.cjs'),HEADERS=require('../security-headers.cjs');
const digest=b=>crypto.createHash('sha256').update(b).digest('hex');
function files(dir,prefix=''){if(fs.lstatSync(dir).isSymbolicLink())throw Error('Linked release paths are not allowed.');return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{const f=path.join(dir,e.name),name=prefix+e.name;if(e.isSymbolicLink())throw Error('Linked release paths are not allowed.');return e.isDirectory()?files(f,name+'/'):[name];});}
function releaseManifest(root=ROOT,assets=ASSETS,headers=HEADERS){
 const out=path.join(root,'dist'),allowed=[...assets,'_headers'].sort(),actual=files(out).sort();if(JSON.stringify(allowed)!==JSON.stringify(actual))throw Error('Release contains missing or unexpected files. Rebuild the public artifact.');
 const source=new Map(),hash=crypto.createHash('sha256');for(const name of assets){const file=path.join(root,name);if(fs.lstatSync(file).isSymbolicLink())throw Error('Linked source files are not allowed.');const b=fs.readFileSync(file);source.set(name,b);hash.update(name).update(b);}hash.update(JSON.stringify(headers));const version=hash.digest('hex').slice(0,20);
 const expectedHeaders='/*\n'+Object.entries({...headers,'Strict-Transport-Security':'max-age=31536000'}).map(([k,v])=>'  '+k+': '+v).join('\n')+'\n';
 const manifest=allowed.map(name=>{const b=fs.readFileSync(path.join(out,name)),expected=name==='_headers'?Buffer.from(expectedHeaders):name==='sw.js'?Buffer.from(source.get(name).toString().replace('security-v1',version)):source.get(name);if(!b.equals(expected))throw Error('Release differs from current source or headers. Rebuild before review.');return {file:name,bytes:b.length,sha256:digest(b)};});
 return {schemaVersion:1,publicVersion:version,files:manifest,artifactDigest:digest(JSON.stringify(manifest)),deploymentAuthorized:false,fieldAcceptance:'blocked',requiredEvidence:['named-phone-browser','physical-printer','native-language-review','participant-scope','independent-review','recovery-drill']};
}
function sanitizeObservation(raw={}){if(!raw||typeof raw!=='object')raw={};const choose=(key,values,fallback)=>values.includes(raw[key])?raw[key]:fallback;return {schemaVersion:1,phase:choose('phase',['cold-start','checkout','restore','upgrade','print'],'unknown'),outcome:choose('outcome',['passed','failed','blocked'],'blocked'),errorClass:choose('errorClass',['none','storage','validation','cancelled','runtime','unavailable'],'unavailable'),durationBucketMs:typeof raw.durationMs==='number'&&Number.isFinite(raw.durationMs)&&raw.durationMs>=0&&raw.durationMs<=300000?Math.ceil(raw.durationMs/100)*100:null,browser:choose('browser',['edge','chrome','firefox','safari'],'unknown'),deviceClass:choose('deviceClass',['desktop','phone','tablet'],'unknown')};}
function observe(page,phase,metadata={}){const started=performance.now();let failed=false;const handler=()=>{failed=true;};page.on('pageerror',handler);return {finish(outcome='passed'){page.off('pageerror',handler);return sanitizeObservation({phase,outcome:failed?'failed':outcome,errorClass:failed?'runtime':'none',durationMs:performance.now()-started,browser:metadata.browser,deviceClass:metadata.deviceClass});}};}
module.exports={releaseManifest,sanitizeObservation,observe};
if(require.main===module){try{const args=process.argv.slice(2);const result=args.length===0?releaseManifest():args.length===2&&args[0]==='--observation'?sanitizeObservation(JSON.parse(fs.readFileSync(args[1],'utf8'))):(()=>{throw Error('Use no arguments for manifest, or --observation with a local JSON file.');})();process.stdout.write(JSON.stringify(result,null,2)+'\n');}catch{process.stderr.write('Pilot evidence could not be generated. Check the input and rebuild the public artifact; no raw input is logged.\n');process.exitCode=1;}}
